Updated to use requirements.txt and Python 2
As the ReadTheDocs build uses Python 2, and currently with Python 3  `sphinxcontrib/contribui.py` fails with `AttributeError: 'Sphinx' object has no attribute 'info'`.